version: "3.8"
services:
  mongodb1:
    image: mongo:4.2.3
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
  mongodb_test:
    image: mongo:4.2.3
    profiles: [ "test" ]
    ports:
      - "27018:27017"
    volumes:
      - ./src/simulation/script:/scripts
