spring:
  data:
    mongodb:
      uri:
      database: smartpv

system:
  measure: true
  collectDevicesStatus: true
  manageDevices: false
  cron:
    measurement: 0 */2 * * * *
    management: 0 */2 * * * *
    collectDevicesStatus: 0 */2 * * * *

counter:
  url: "https://smartpv-counter.herokuapp.com/"