package com.domain.model.farm;

public enum DeviceType {
  SUPLA_METER_MEW01,
  SUPLA_CONSUMPTION_ONOFF_ROW01,
  SUPLA_CONSUMPTION_READ_ROW01,
  SUPLA_STATUS,
  SUPLA_ELECTRIC_METER,

  SUPLA_SWITCH,
}
