spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/smartPV
      database: smartPV

system:
  measure: true
  collectDevicesStatus: true
  manageDevices: false
  cron:
    measurement: "*/5 * * * * *"
    management: "*/5 * * * * *"
    collectDevicesStatus: "*/5 * * * * *"

counter:
  url: http://127.0.0.1:5000/
  endpoints:
    simpson: simpson
    average: average
