spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/smartPV
      database: smartPV

system:
  measure: true
  collectDevicesStatus: true
  manageDevices: true
  cron:
    measurement: "*/5 * * * * *"
    management: "*/5 * * * * *"
    collectDevicesStatus: "*/5 * * * * *"