spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/smartPV
      database: smartPV

system:
  measure: true
  collectDevicesStatus: false
  manageDevices: false
  cron:
    measurement: 0 */5 * * * *
    management: 0 */5 * * * *
    collectDevicesStatus: 0 */5 * * * *