spring:
  data:
    mongodb:
      uri: mongodb+srv://kuba:kuba@cluster0.qd1lc.mongodb.net/smartPV?retryWrites=true&w=majority
      database: smartPV

measurement-cron: 0 */1 * * * *
management-cron: 0 */1 * * * *