db.getCollection('measuringDeviceEntity').remove({})
db.getCollection('measurementEntity').remove({})
db.getCollection('measurementSumEntity').remove({})
db.getCollection('consumerDeviceEntity').remove({})
db.getCollection('farmEntity').remove({})
